- app/src/main/java/mz/org/fgh/idartlite/dao/GenericServiceDao.java
adicao do pacote dao e classe generica
> adicao da classe generica e do pacote dao.

- app/src/main/java/mz/org/fgh/idartlite/dao/DispenseDao.java
- app/src/main/java/mz/org/fgh/idartlite/dao/DispenseDaoImpl.java
- app/src/main/java/mz/org/fgh/idartlite/dao/DispensedDrugDao.java
- app/src/main/java/mz/org/fgh/idartlite/dao/DispensedDrugDaoImpl.java
- app/src/main/java/mz/org/fgh/idartlite/dao/DrugDao.java
- app/src/main/java/mz/org/fgh/idartlite/dao/DrugDaoImpl.java
- app/src/main/java/mz/org/fgh/idartlite/dao/StockDao.java
- app/src/main/java/mz/org/fgh/idartlite/dao/StockDaoImpl.java
- app/src/main/java/mz/org/fgh/idartlite/model/DiseaseType.java
- app/src/main/java/mz/org/fgh/idartlite/model/Dispense.java
- app/src/main/java/mz/org/fgh/idartlite/model/DispenseType.java
- app/src/main/java/mz/org/fgh/idartlite/model/DispensedDrug.java
- app/src/main/java/mz/org/fgh/idartlite/model/Drug.java
- app/src/main/java/mz/org/fgh/idartlite/model/Form.java
- app/src/main/java/mz/org/fgh/idartlite/model/RegimenDrug.java
- app/src/main/java/mz/org/fgh/idartlite/model/Stock.java
- app/src/main/java/mz/org/fgh/idartlite/service/DispenseService.java
- app/src/main/java/mz/org/fgh/idartlite/service/StockService.java
novas classes adiconadas com os seus DAOs
> novas classes adiconadas

- .idea/compiler.xml
- .idea/misc.xml
- .idea/uiDesigner.xml
- app/src/main/java/mz/org/fgh/idartlite/dao/ClinicDao.java
- app/src/main/java/mz/org/fgh/idartlite/dao/ClinicDaoImpl.java
- app/src/main/java/mz/org/fgh/idartlite/dao/EpisodeDao.java
- app/src/main/java/mz/org/fgh/idartlite/dao/EpisodeDaoImpl.java
- app/src/main/java/mz/org/fgh/idartlite/dao/PatientDao.java
- app/src/main/java/mz/org/fgh/idartlite/dao/PatientDaoImpl.java
- app/src/main/java/mz/org/fgh/idartlite/dao/PharmacyTypeDao.java
- app/src/main/java/mz/org/fgh/idartlite/dao/PharmacyTypeDaoImpl.java
- app/src/main/java/mz/org/fgh/idartlite/dao/PrescriptionDao.java
- app/src/main/java/mz/org/fgh/idartlite/dao/PrescriptionDaoImpl.java
- app/src/main/java/mz/org/fgh/idartlite/dao/TherapeuticLineDao.java
- app/src/main/java/mz/org/fgh/idartlite/dao/TherapeuticLineDaoImpl.java
- app/src/main/java/mz/org/fgh/idartlite/dao/TherapeuticRegimenDao.java
- app/src/main/java/mz/org/fgh/idartlite/dao/TherapeuticRegimenDaoImpl.java
- app/src/main/java/mz/org/fgh/idartlite/model/Clinic.java
- app/src/main/java/mz/org/fgh/idartlite/model/Episode.java
- app/src/main/java/mz/org/fgh/idartlite/model/Patient.java
- app/src/main/java/mz/org/fgh/idartlite/model/PharmacyType.java
- app/src/main/java/mz/org/fgh/idartlite/model/Prescription.java
- app/src/main/java/mz/org/fgh/idartlite/model/RegimenDrugs.java
- app/src/main/java/mz/org/fgh/idartlite/model/TherapeuticLine.java
- app/src/main/java/mz/org/fgh/idartlite/model/TherapeuticRegimen.java
> commit das entidades e daos

- app/src/main/java/mz/org/fgh/idartlite/dao/EpisodeDao.java
- app/src/main/java/mz/org/fgh/idartlite/dao/EpisodeDaoImpl.java
- app/src/main/java/mz/org/fgh/idartlite/dao/IdartLiteDataBaseHelper.java
- app/src/main/java/mz/org/fgh/idartlite/dao/PrescriptionDao.java
- app/src/main/java/mz/org/fgh/idartlite/dao/PrescriptionDaoImpl.java
- app/src/main/java/mz/org/fgh/idartlite/model/DiseaseType.java
- app/src/main/java/mz/org/fgh/idartlite/model/Dispense.java
- app/src/main/java/mz/org/fgh/idartlite/model/DispenseType.java
- app/src/main/java/mz/org/fgh/idartlite/model/DispensedDrug.java
- app/src/main/java/mz/org/fgh/idartlite/model/Drug.java
- app/src/main/java/mz/org/fgh/idartlite/model/Form.java
- app/src/main/java/mz/org/fgh/idartlite/model/Stock.java
- app/src/main/java/mz/org/fgh/idartlite/service/EpisodeService.java
- app/src/main/java/mz/org/fgh/idartlite/service/PrescriptionService.java
classes de servicos e querys  alteracoes nas classes do modelo
> classes de servicos e querys  alteracoes nas classes do modelo

- app/src/main/java/mz/org/fgh/idartlite/model/Dispense.java
- app/src/main/java/mz/org/fgh/idartlite/model/DispensedDrug.java
- app/src/main/java/mz/org/fgh/idartlite/model/PrescribedDrug.java
Adição de entidades ao projecto
> Adição de entidades ao projecto-IM

- app/src/main/java/mz/org/fgh/idartlite/adapter/ContentListPatientAdapter.java
- app/src/main/java/mz/org/fgh/idartlite/dao/DiseaseTypeDao.java
- app/src/main/java/mz/org/fgh/idartlite/dao/DiseaseTypeDaoImpl.java
- app/src/main/java/mz/org/fgh/idartlite/dao/DispenseTypeDao.java
- app/src/main/java/mz/org/fgh/idartlite/dao/DispenseTypeDaoImpl.java
- app/src/main/java/mz/org/fgh/idartlite/dao/FormDao.java
- app/src/main/java/mz/org/fgh/idartlite/dao/FormDaoImpl.java
- app/src/main/java/mz/org/fgh/idartlite/dao/IdartLiteDataBaseHelper.java
- app/src/main/java/mz/org/fgh/idartlite/dao/PrescribedDrugDao.java
- app/src/main/java/mz/org/fgh/idartlite/dao/PrescribedDrugDaoImpl.java
- app/src/main/java/mz/org/fgh/idartlite/dao/RegimenDrugDao.java
- app/src/main/java/mz/org/fgh/idartlite/dao/RegimenDrugDaoImpl.java
- app/src/main/java/mz/org/fgh/idartlite/model/Dispense.java
- app/src/main/java/mz/org/fgh/idartlite/model/Prescription.java
- app/src/main/java/mz/org/fgh/idartlite/service/ClinicService.java
- app/src/main/java/mz/org/fgh/idartlite/service/PatientService.java
- app/src/main/java/mz/org/fgh/idartlite/service/PharmacyTypeService.java
- app/src/main/java/mz/org/fgh/idartlite/viewmodel/PatientVM.java
- app/src/main/res/drawable/ic_logo_content_list.xml
> add new method and screen

- app/src/main/java/mz/org/fgh/idartlite/model/Dispense.java
- app/src/main/java/mz/org/fgh/idartlite/model/DispensedDrug.java
- app/src/main/java/mz/org/fgh/idartlite/model/Prescription.java
- app/src/main/java/mz/org/fgh/idartlite/view/patient/EpisodeDetailsActivity.java
- app/src/main/java/mz/org/fgh/idartlite/view/patient/EpisodeFragment.java
- app/src/main/res/layout/patient_dispense_row.xml
- app/src/main/res/layout/patient_episode_row.xml
- app/src/main/res/layout/patient_prescription_row.xml
- app/src/main/res/values-pt/strings.xml
- app/src/main/res/values/strings.xml
Mapeamento das Telas de Lista de Prescricao e Episodio
> Mapeamento das Telas de Lista de Prescricao e Episodio(IM-6)

- app/src/main/res/values-pt/strings.xml
- app/src/main/res/values/strings.xml
adicao de strings no strings.xml
> adicao de strings

- app/src/main/java/mz/org/fgh/idartlite/model/Patient.java
- app/src/main/java/mz/org/fgh/idartlite/view/LoginActivity.java
- app/src/main/java/mz/org/fgh/idartlite/view/patient/PatientActivity.java
- app/src/main/java/mz/org/fgh/idartlite/view/patient/PatientDetailsFragment.java
- app/src/main/res/drawable/ic_row_dados_pessoais.xml
- app/src/main/res/layout/activity_episode_details.xml
- app/src/main/res/layout/activity_login.xml
- app/src/main/res/layout/activity_search_patient.xml
- app/src/main/res/layout/pacinte_details_fragment.xml
- app/src/main/res/layout/patient_dispense_row.xml
- app/src/main/res/values-pt/strings.xml
- app/src/main/res/values/strings.xml
> new screen

- app/src/main/java/mz/org/fgh/idartlite/adapter/StockTabAdapter.java
- app/src/main/java/mz/org/fgh/idartlite/view/HomeActivity.java
- app/src/main/java/mz/org/fgh/idartlite/view/patient/adapter/PatientTabAdapter.java
- app/src/main/java/mz/org/fgh/idartlite/view/stock/StockActivity.java
- app/src/main/java/mz/org/fgh/idartlite/view/stock/StockEntranceFragment.java
- app/src/main/java/mz/org/fgh/idartlite/view/stock/StockInventoryFragment.java
- app/src/main/java/mz/org/fgh/idartlite/viewmodel/HomeVM.java
- app/src/main/java/mz/org/fgh/idartlite/viewmodel/PatientVM.java
- app/src/main/java/mz/org/fgh/idartlite/viewmodel/StockVM.java
- app/src/main/res/drawable/ic_stock_entrance.xml
- app/src/main/res/drawable/ic_stock_inventory.xml
- app/src/main/res/layout/fragment_stock_entrance.xml
- app/src/main/res/layout/fragment_stock_inventory.xml
- app/src/main/res/values-pt/strings.xml
- app/src/main/res/values/strings.xml
> add stock screen

- app/src/main/AndroidManifest.xml
- app/src/main/java/mz/org/fgh/idartlite/model/Episode.java
- app/src/main/java/mz/org/fgh/idartlite/view/patient/CreateEpisodeActivity.java
- app/src/main/java/mz/org/fgh/idartlite/view/patient/EpisodeFragment.java
- app/src/main/java/mz/org/fgh/idartlite/view/patient/adapter/EpisodeAdapter.java
- app/src/main/java/mz/org/fgh/idartlite/viewmodel/EpisodeVM.java
- app/src/main/res/drawable/ic_baseline_calendar_today_24.xml
- app/src/main/res/drawable/ic_baseline_format_list_bulleted_24.xml
- app/src/main/res/drawable/ic_round_check_circle_24.xml
- app/src/main/res/drawable/ic_round_notes_24.xml
- app/src/main/res/layout/create_activity_episode.xml
- app/src/main/res/layout/patient_episode_row.xml
- app/src/main/res/values-pt/strings.xml
- app/src/main/res/values/strings.xml
criar Episodio , mapeamento tela episodio row
> criar Episodio , mapeamento tela episodio row

- .idea/.gitignore
- .idea/codeStyles/Project.xml
- .idea/codeStyles/codeStyleConfig.xml
- .idea/dbnavigator.xml
- app/src/main/java/mz/org/fgh/idartlite/model/Dispense.java
- app/src/main/java/mz/org/fgh/idartlite/model/DispenseType.java
- app/src/main/java/mz/org/fgh/idartlite/model/Prescription.java
- app/src/main/java/mz/org/fgh/idartlite/model/User.java
- app/src/main/java/mz/org/fgh/idartlite/service/DispenseService.java
- app/src/main/java/mz/org/fgh/idartlite/service/DispenseTypeService.java
- app/src/main/java/mz/org/fgh/idartlite/service/TherapeuthicLineService.java
- app/src/main/java/mz/org/fgh/idartlite/service/TherapheuticRegimenService.java
- app/src/main/java/mz/org/fgh/idartlite/viewmodel/LoginVM.java
- app/src/main/res/layout/patient_dispense_row.xml
- app/src/main/res/values-pt/strings.xml
- app/src/main/res/values/strings.xml
> commit listagem de dispensas

- app/src/main/java/mz/org/fgh/idartlite/model/Episode.java
- app/src/main/java/mz/org/fgh/idartlite/service/EpisodeService.java
- app/src/main/java/mz/org/fgh/idartlite/viewmodel/LoginVM.java
modificao do modelo de episodioo
> modificao do modelo de episodioo

- .idea/codeStyles/Project.xml
- .idea/dbnavigator.xml
- app/src/main/AndroidManifest.xml
- app/src/main/java/mz/org/fgh/idartlite/view/patient/CreateDispenseActivity.java
- app/src/main/java/mz/org/fgh/idartlite/view/patient/CreateEpisodeActivity.java
- app/src/main/java/mz/org/fgh/idartlite/view/patient/DispenseFragment.java
- app/src/main/java/mz/org/fgh/idartlite/viewmodel/DispenseVM.java
- app/src/main/res/layout/activity_create_dispense.xml
- app/src/main/res/layout/fragment_dispense.xml
> commit tela de cadastro de dispensa(aviamento)

- .idea/codeStyles/Project.xml
- app/src/main/java/mz/org/fgh/idartlite/dao/EpisodeDaoImpl.java
- app/src/main/java/mz/org/fgh/idartlite/service/DispenseService.java
- app/src/main/java/mz/org/fgh/idartlite/service/EpisodeService.java
- app/src/main/java/mz/org/fgh/idartlite/view/patient/CreateEpisodeActivity.java
- app/src/main/java/mz/org/fgh/idartlite/view/patient/EpisodeFragment.java
- app/src/main/java/mz/org/fgh/idartlite/view/patient/adapter/EpisodeAdapter.java
- app/src/main/java/mz/org/fgh/idartlite/viewmodel/EpisodeVM.java
- app/src/main/java/mz/org/fgh/idartlite/viewmodel/LoginVM.java
- app/src/main/res/layout/create_activity_episode.xml
- app/src/main/res/layout/patient_episode_row.xml
- app/src/main/res/values/strings.xml
criacao e listagem de episodios
> criacao e listagem de episodios

- app/src/main/java/mz/org/fgh/idartlite/dao/PatientDao.java
- app/src/main/java/mz/org/fgh/idartlite/dao/PatientDaoImpl.java
- app/src/main/java/mz/org/fgh/idartlite/service/PatientService.java
- app/src/main/java/mz/org/fgh/idartlite/view/SearchPatientActivity.java
- app/src/main/java/mz/org/fgh/idartlite/viewmodel/HomeVM.java
- app/src/main/java/mz/org/fgh/idartlite/viewmodel/PatientVM.java
Melhoria da lista que mostra os pacientes e do Metodo de Pesquisa do Paciente
> Melhoria da lista que mostra os pacientes e do Metodo de Pesquisa do Paciente(Im-12)

- .idea/codeStyles/Project.xml
- .idea/dbnavigator.xml
- app/src/main/AndroidManifest.xml
- app/src/main/java/mz/org/fgh/idartlite/dao/PrescriptionDao.java
- app/src/main/java/mz/org/fgh/idartlite/dao/PrescriptionDaoImpl.java
- app/src/main/java/mz/org/fgh/idartlite/model/Dispense.java
- app/src/main/java/mz/org/fgh/idartlite/service/DispenseDrugService.java
- app/src/main/java/mz/org/fgh/idartlite/service/DispenseService.java
- app/src/main/java/mz/org/fgh/idartlite/service/DispenseTypeService.java
- app/src/main/java/mz/org/fgh/idartlite/service/PrescriptionService.java
- app/src/main/java/mz/org/fgh/idartlite/view/patient/CreateDispenseActivity.java
- app/src/main/java/mz/org/fgh/idartlite/viewmodel/DispenseVM.java
- app/src/main/java/mz/org/fgh/idartlite/viewmodel/PrescriptionVM.java
- app/src/main/res/layout/activity_create_dispense.xml
cadastro da dispensa(aviamento)
> cadastro da dispensa

- app/src/main/java/mz/org/fgh/idartlite/view/patient/PatientDetailsFragment.java
- app/src/main/java/mz/org/fgh/idartlite/viewmodel/PatientDetailsVM.java
- app/src/main/res/layout/pacinte_details_fragment.xml
Change layout of patient detalis
> Change layout of patient detalis

- .idea/codeStyles/Project.xml
- .idea/dbnavigator.xml
- app/src/main/java/mz/org/fgh/idartlite/model/Drug.java
- app/src/main/java/mz/org/fgh/idartlite/service/DispenseService.java
- app/src/main/java/mz/org/fgh/idartlite/service/StockService.java
- app/src/main/java/mz/org/fgh/idartlite/view/patient/CreateDispenseActivity.java
- app/src/main/java/mz/org/fgh/idartlite/view/patient/DispenseFragment.java
- app/src/main/java/mz/org/fgh/idartlite/viewmodel/DispenseVM.java
- app/src/main/java/mz/org/fgh/idartlite/viewmodel/LoginVM.java
- app/src/main/res/values-pt/strings.xml
- app/src/main/res/values/strings.xml
Melhorias na criacao do aviamento
> Melhorias no cadastro da dispensa

- .idea/codeStyles/Project.xml
- app/src/main/AndroidManifest.xml
- app/src/main/java/mz/org/fgh/idartlite/base/BaseService.java
- app/src/main/java/mz/org/fgh/idartlite/dao/DispenseDao.java
- app/src/main/java/mz/org/fgh/idartlite/dao/DispenseDaoImpl.java
- app/src/main/java/mz/org/fgh/idartlite/dao/EpisodeDao.java
- app/src/main/java/mz/org/fgh/idartlite/dao/EpisodeDaoImpl.java
- app/src/main/java/mz/org/fgh/idartlite/model/Episode.java
- app/src/main/java/mz/org/fgh/idartlite/service/DispenseService.java
- app/src/main/java/mz/org/fgh/idartlite/service/EpisodeService.java
- app/src/main/java/mz/org/fgh/idartlite/util/DateUtilitis.java
- app/src/main/java/mz/org/fgh/idartlite/view/patient/EpisodeActivity.java
- app/src/main/java/mz/org/fgh/idartlite/view/patient/EpisodeFragment.java
- app/src/main/java/mz/org/fgh/idartlite/viewmodel/EpisodeVM.java
- app/src/main/res/layout/activity_prescription.xml
- app/src/main/res/layout/episode_activity.xml
- app/src/main/res/layout/patient_episode_row.xml
- app/src/main/res/values/strings.xml
criar e actualizar episodio
passagem das querys do dispense service para o DispenseDao
> criar e actualizar episodio passagem das querys do dispense service para o DispenseDao

- app/src/main/java/mz/org/fgh/idartlite/rest/RESTServiceHandler.java
- app/src/main/java/mz/org/fgh/idartlite/service/ClinicService.java
- app/src/main/java/mz/org/fgh/idartlite/service/DiseaseTypeService.java
- app/src/main/java/mz/org/fgh/idartlite/service/DispenseTypeService.java
- app/src/main/java/mz/org/fgh/idartlite/service/DrugService.java
- app/src/main/java/mz/org/fgh/idartlite/service/EpisodeService.java
- app/src/main/java/mz/org/fgh/idartlite/service/FormService.java
- app/src/main/java/mz/org/fgh/idartlite/service/PatientService.java
- app/src/main/java/mz/org/fgh/idartlite/service/PharmacyTypeService.java
- app/src/main/java/mz/org/fgh/idartlite/service/PrescriptionService.java
- app/src/main/java/mz/org/fgh/idartlite/service/RegimenDrugsService.java
- app/src/main/java/mz/org/fgh/idartlite/service/TherapeuthicLineService.java
- app/src/main/java/mz/org/fgh/idartlite/service/TherapheuticRegimenService.java
- app/src/main/java/mz/org/fgh/idartlite/service/restService/RestClinicService.java
- app/src/main/java/mz/org/fgh/idartlite/service/restService/RestDiseaseTypeService.java
- app/src/main/java/mz/org/fgh/idartlite/service/restService/RestDispenseService.java
- app/src/main/java/mz/org/fgh/idartlite/service/restService/RestDispenseTypeService.java
- app/src/main/java/mz/org/fgh/idartlite/service/restService/RestDrugService.java
- app/src/main/java/mz/org/fgh/idartlite/service/restService/RestEpisodeService.java
- app/src/main/java/mz/org/fgh/idartlite/service/restService/RestFormService.java
- app/src/main/java/mz/org/fgh/idartlite/service/restService/RestPatientService.java
- app/src/main/java/mz/org/fgh/idartlite/service/restService/RestPharmacyTypeService.java
- app/src/main/java/mz/org/fgh/idartlite/service/restService/RestPrescriptionService.java
- app/src/main/java/mz/org/fgh/idartlite/service/restService/RestStockService.java
- app/src/main/java/mz/org/fgh/idartlite/service/restService/RestTherapeuticLineService.java
- app/src/main/java/mz/org/fgh/idartlite/service/restService/RestTherapeuticRegimenService.java
- app/src/main/java/mz/org/fgh/idartlite/service/restService/RestUserService.java
> Rest Services for Data and Configurations

- app/src/main/java/mz/org/fgh/idartlite/base/BaseService.java
> I dart mobile v1

- app/src/main/java/mz/org/fgh/idartlite/view/stock/StockActivity.java
- app/src/main/java/mz/org/fgh/idartlite/view/stock/StockEntranceActivity.java
> adding toolbar

- app/src/main/java/mz/org/fgh/idartlite/model/Clinic.java
- app/src/main/res/layout/activity_home.xml
> add clinic to string

- .idea/codeStyles/Project.xml
- app/src/main/java/mz/org/fgh/idartlite/view/patient/EpisodeActivity.java
- app/src/main/java/mz/org/fgh/idartlite/view/patient/EpisodeFragment.java
- app/src/main/java/mz/org/fgh/idartlite/viewmodel/EpisodeVM.java
> fixes na busca de episodios.

- app/src/main/java/mz/org/fgh/idartlite/base/BaseService.java
- app/src/main/java/mz/org/fgh/idartlite/rest/ExecutorThreadProvider.java
- app/src/main/java/mz/org/fgh/idartlite/service/restService/RestClinicService.java
- app/src/main/java/mz/org/fgh/idartlite/view/SplashActivity.java
Centralização da thread usada no volley
> Correção do erro ao carregar a app com o servidor central offline

- app/src/main/java/mz/org/fgh/idartlite/view/stock/StockEntranceActivity.java
> alter stock movement

- app/src/main/java/mz/org/fgh/idartlite/util/SecurePreferences.java
- app/src/main/java/mz/org/fgh/idartlite/view/LoginActivity.java
- app/src/main/java/mz/org/fgh/idartlite/view/patient/EpisodeActivity.java
- app/src/main/java/mz/org/fgh/idartlite/view/patient/EpisodeFragment.java
- app/src/main/java/mz/org/fgh/idartlite/viewmodel/LoginVM.java
- app/src/main/res/layout/activity_login.xml
- app/src/main/res/values/strings.xml
fixes na busca de episodios.
adicao da funcionalidade de remember me (gravar)
> fixes na busca de episodios. adicao da funcionalidade de remember me (gravar)

- app/src/main/java/mz/org/fgh/idartlite/view/patient/EpisodeFragment.java
> fixes na remocao episodios.

- .idea/codeStyles/Project.xml
- app/src/main/java/mz/org/fgh/idartlite/service/EpisodeService.java
- app/src/main/java/mz/org/fgh/idartlite/view/patient/EpisodeActivity.java
- app/src/main/java/mz/org/fgh/idartlite/view/patient/EpisodeFragment.java
- app/src/main/java/mz/org/fgh/idartlite/viewmodel/EpisodeVM.java
- app/src/main/res/menu/edit_remove_menu.xml
- app/src/main/res/values/strings.xml
Adicao do visualizar detalhes no episodios (IM-27)
> Adicao do visualizar detalhes no episodios (IM-27)

- app/src/main/java/mz/org/fgh/idartlite/dao/UserDaoImpl.java
- app/src/main/java/mz/org/fgh/idartlite/service/UserService.java
- app/src/main/java/mz/org/fgh/idartlite/view/patient/EpisodeActivity.java
- app/src/main/java/mz/org/fgh/idartlite/viewmodel/LoginVM.java
encriptacao da senha ao gravar e ao comparar no momento de Login
> encriptacao da senha ao gravar e ao comparar no momento de Login

- .idea/codeStyles/Project.xml
- .idea/dbnavigator.xml
- app/src/main/java/mz/org/fgh/idartlite/service/DispenseService.java
- app/src/main/java/mz/org/fgh/idartlite/view/patient/CreateDispenseActivity.java
- app/src/main/java/mz/org/fgh/idartlite/viewmodel/DispenseVM.java
Cadastro dispensa validacoes e listagem de prescribeddrugs
> Cadastro dispensa validacoes e listagem de prescribeddrugs

- .idea/codeStyles/Project.xml
- app/src/main/java/mz/org/fgh/idartlite/view/patient/EpisodeActivity.java
> mudanca de startSpn par stop

- app/src/main/java/mz/org/fgh/idartlite/view/stock/StockEntranceActivity.java
- app/src/main/res/layout/activity_stock_entrance.xml
troca de spinner de medicamentos por autoCompleteTextView
> troca de spinner de medicamentos por autoCompleteTextView

- app/src/main/java/mz/org/fgh/idartlite/view/patient/PrescriptionActivity.java
- app/src/main/res/layout/activity_prescription.xml
troca de spinner de medicamentos por autoCompleteTextView na prescricao
> troca de spinner de medicamentos por autoCompleteTextView na prescricao

- app/src/main/java/mz/org/fgh/idartlite/base/BaseService.java
- app/src/main/java/mz/org/fgh/idartlite/rest/RESTServiceHandler.java
- app/src/main/java/mz/org/fgh/idartlite/service/restService/RestStockService.java
> Stock Control From Rest

- app/src/main/java/mz/org/fgh/idartlite/base/SearchVM.java
- app/src/main/java/mz/org/fgh/idartlite/service/DispenseService.java
- app/src/main/java/mz/org/fgh/idartlite/service/EpisodeService.java
- app/src/main/java/mz/org/fgh/idartlite/service/restService/RestClinicService.java
- app/src/main/java/mz/org/fgh/idartlite/service/restService/RestDispenseService.java
- app/src/main/java/mz/org/fgh/idartlite/view/SplashActivity.java
- app/src/main/java/mz/org/fgh/idartlite/view/patient/EpisodeFragment.java
- app/src/main/java/mz/org/fgh/idartlite/view/stock/StockEntranceFragment.java
- app/src/main/java/mz/org/fgh/idartlite/viewmodel/EpisodeVM.java
- app/src/main/java/mz/org/fgh/idartlite/viewmodel/SplashVM.java
- app/src/main/res/layout/patient_dispense_row.xml
- app/src/main/res/layout/patient_episode_row.xml
- app/src/main/res/layout/patient_prescription_row.xml
> fixes da apresentacao

- .idea/codeStyles/Project.xml
- app/src/main/java/mz/org/fgh/idartlite/model/Episode.java
- app/src/main/java/mz/org/fgh/idartlite/service/restService/RestDiseaseTypeService.java
- app/src/main/java/mz/org/fgh/idartlite/view/LoginActivity.java
- app/src/main/java/mz/org/fgh/idartlite/view/SearchPatientActivity.java
- app/src/main/java/mz/org/fgh/idartlite/view/patient/EpisodeActivity.java
- app/src/main/java/mz/org/fgh/idartlite/view/patient/EpisodeFragment.java
- app/src/main/java/mz/org/fgh/idartlite/view/patient/PatientActivity.java
- app/src/main/java/mz/org/fgh/idartlite/view/patient/PrescriptionActivity.java
- app/src/main/java/mz/org/fgh/idartlite/view/patient/PrescriptionFragment.java
- app/src/main/java/mz/org/fgh/idartlite/view/stock/StockEntranceActivity.java
- app/src/main/java/mz/org/fgh/idartlite/view/stock/StockEntranceFragment.java
- app/src/main/java/mz/org/fgh/idartlite/viewmodel/EpisodeVM.java
- app/src/main/java/mz/org/fgh/idartlite/viewmodel/LoginVM.java
- app/src/main/res/layout/activity_about.xml
- app/src/main/res/values-pt/strings.xml
- app/src/main/res/values/strings.xml
melhoria e adicao de mensagens no ficheiro strings
> melhoria e adicao de mensagens no ficheiro strings

- app/src/main/java/mz/org/fgh/idartlite/service/DrugService.java
- app/src/main/res/layout/content_patient.xml
- app/src/main/res/layout/pacinte_details_fragment.xml
- app/src/main/res/values/strings.xml
correcao de mensagens de ingles para portugues e acentuacao
> correcao de mensagens de ingles para portugues e acentuacao

- app/src/main/res/layout/activity_create_dispense.xml
- app/src/main/res/layout/activity_prescription.xml
A aplicação mostra os dados do aviamento mas como se fosse uma tela para adição.
Aparece a palavra Adicionar nos 2 grupos:
Adicionar Aviamento - Dados Iniciais
Adicionar Aviamento - Medicamentos
> Ecra de Detalhes do aviamento

- app/src/main/java/mz/org/fgh/idartlite/service/DrugService.java
- app/src/main/java/mz/org/fgh/idartlite/view/patient/CreateDispenseActivity.java
- app/src/main/java/mz/org/fgh/idartlite/view/patient/PrescriptionActivity.java
- app/src/main/java/mz/org/fgh/idartlite/view/stock/StockEntranceActivity.java
- app/src/main/java/mz/org/fgh/idartlite/viewmodel/DispenseVM.java
- app/src/main/java/mz/org/fgh/idartlite/viewmodel/PrescriptionVM.java
- app/src/main/res/layout/activity_stock_entrance.xml
- app/src/main/res/layout/layout_autocomplete_text_view.xml
> fixes no autoCompleteTextView

- app/src/main/java/mz/org/fgh/idartlite/TaskSchedule/workScheduler/RestPostPatientDataWorkerScheduler.java
- app/src/main/java/mz/org/fgh/idartlite/dao/EpisodeDao.java
- app/src/main/java/mz/org/fgh/idartlite/dao/EpisodeDaoImpl.java
- app/src/main/java/mz/org/fgh/idartlite/model/SyncEpisode.java
- app/src/main/java/mz/org/fgh/idartlite/service/EpisodeService.java
- app/src/main/java/mz/org/fgh/idartlite/service/restService/RestEpisodeService.java
- app/src/main/java/mz/org/fgh/idartlite/service/restService/RestRunDataForTestService.java
- app/src/main/java/mz/org/fgh/idartlite/view/patient/EpisodeActivity.java
> Envio de EPisodio via rest

- app/src/main/AndroidManifest.xml
- app/src/main/java/mz/org/fgh/idartlite/adapter/ContentListDispenseAdapter.java
- app/src/main/java/mz/org/fgh/idartlite/adapter/ReportListAdapter.java
- app/src/main/java/mz/org/fgh/idartlite/dao/DispenseDao.java
- app/src/main/java/mz/org/fgh/idartlite/dao/DispenseDaoImpl.java
- app/src/main/java/mz/org/fgh/idartlite/service/DispenseService.java
- app/src/main/java/mz/org/fgh/idartlite/view/reports/DispenseReportActivity.java
- app/src/main/java/mz/org/fgh/idartlite/view/reports/ReportTypeActivity.java
- app/src/main/java/mz/org/fgh/idartlite/view/reports/ReportsListingActivity.java
- app/src/main/java/mz/org/fgh/idartlite/viewmodel/DispenseReportVM.java
- app/src/main/java/mz/org/fgh/idartlite/viewmodel/ReportTypeVM.java
- app/src/main/res/layout/activity_report_type.xml
- app/src/main/res/layout/activity_reports_listing.xml
- app/src/main/res/layout/content_dispenses_report.xml
- app/src/main/res/layout/content_report.xml
- app/src/main/res/layout/dispense_report.xml
- app/src/main/res/values-pt/strings.xml
- app/src/main/res/values/strings.xml
Relatorio de Dispensas da Farmacia
> Relatorio de Dispensas da Farmacia

- .idea/codeStyles/Project.xml
- .idea/dbnavigator.xml
- app/build.gradle
- app/src/main/AndroidManifest.xml
- app/src/main/java/mz/org/fgh/idartlite/adapter/ReportListAdapter.java
- app/src/main/java/mz/org/fgh/idartlite/common/ListbleReportRecycleViewAdapter.java
- app/src/main/java/mz/org/fgh/idartlite/dao/DispenseDao.java
- app/src/main/java/mz/org/fgh/idartlite/dao/DispenseDaoImpl.java
- app/src/main/java/mz/org/fgh/idartlite/dao/DispensedDrugDao.java
- app/src/main/java/mz/org/fgh/idartlite/dao/DispensedDrugDaoImpl.java
- app/src/main/java/mz/org/fgh/idartlite/model/StockReportData.java
- app/src/main/java/mz/org/fgh/idartlite/service/DispenseService.java
- app/src/main/java/mz/org/fgh/idartlite/util/DateUtilitis.java
- app/src/main/java/mz/org/fgh/idartlite/view/reports/DispenseReportActivity.java
- app/src/main/java/mz/org/fgh/idartlite/view/reports/ReportTypeActivity.java
- app/src/main/java/mz/org/fgh/idartlite/view/reports/StockAlertReportActivity.java
- app/src/main/java/mz/org/fgh/idartlite/viewmodel/DispenseReportVM.java
- app/src/main/res/layout/activity_stock_alert_report.xml
- app/src/main/res/layout/content_dispenses_report.xml
- app/src/main/res/layout/content_report.xml
- app/src/main/res/layout/dispense_report.xml
- app/src/main/res/layout/headeritem_report.xml
- app/src/main/res/layout/listable_item_report.xml
- app/src/main/res/values-pt/strings.xml
- app/src/main/res/values/strings.xml
relatorio de dispensas e alerta de stock
> relatorio de dispensas e alerta de stock

- app/src/main/java/mz/org/fgh/idartlite/base/service/BaseServiceFactory.java
- app/src/main/java/mz/org/fgh/idartlite/view/stock/inventory/IventoryActivity.java
- app/src/main/java/mz/org/fgh/idartlite/view/stock/panel/DestroiedStockListFragment.java
- app/src/main/java/mz/org/fgh/idartlite/view/stock/panel/StockInventoryListingFragment.java
- app/src/main/java/mz/org/fgh/idartlite/viewmodel/prescription/PrescriptionVM.java
- app/src/main/java/mz/org/fgh/idartlite/viewmodel/stock/DestroiedStockListingVM.java
- app/src/main/java/mz/org/fgh/idartlite/viewmodel/stock/IventoryListingVM.java
- app/src/main/res/drawable/listable_edit_text_border.xml
- app/src/main/res/drawable/listable_edittext_focused.xml
- app/src/main/res/drawable/listable_edittext_normal.xml
- app/src/main/res/drawable/listable_edittext_pressed.xml
- app/src/main/res/layout/headeritem.xml
- app/src/main/res/layout/listable_item.xml
Destruir quantidade de Medicamentos no Stock IM-44
Melhoria do código base
> Inventario do Stock IM-46

- .idea/codeStyles/Project.xml
- app/build.gradle
- app/src/main/java/mz/org/fgh/idartlite/util/Utilities.java
- app/src/main/java/mz/org/fgh/idartlite/view/patientSearch/NewPatientSearchActivity.java
- app/src/main/java/mz/org/fgh/idartlite/view/reports/DispenseReportActivity.java
- app/src/main/java/mz/org/fgh/idartlite/view/reports/FILAReportActivity.java
- app/src/main/java/mz/org/fgh/idartlite/view/reports/PatientRegisterReportActivity.java
- app/src/main/java/mz/org/fgh/idartlite/viewmodel/patient/NewPatientSearchVM.java
- app/src/main/res/layout/activity_patient_home.xml
adicao de logo no relatorios em pdf , melhorias e fixes
> adicao de logo no relatorios em pdf , melhorias e fixes

- app/src/main/java/mz/org/fgh/idartlite/base/model/BaseModel.java
- app/src/main/java/mz/org/fgh/idartlite/model/DestroyedDrug.java
- app/src/main/java/mz/org/fgh/idartlite/model/ReferedStockMoviment.java
- app/src/main/java/mz/org/fgh/idartlite/model/inventory/InventoryRelatedObject.java
- app/src/main/java/mz/org/fgh/idartlite/model/inventory/Iventory.java
- app/src/main/java/mz/org/fgh/idartlite/viewmodel/stock/DestroyStockVM.java
- app/src/main/java/mz/org/fgh/idartlite/viewmodel/stock/InventoryVM.java
- app/src/main/java/mz/org/fgh/idartlite/viewmodel/stock/ReferedStockMovimentVM.java
- app/src/main/res/values-pt/strings.xml
- app/src/main/res/values/strings.xml
Validation messages moved to strings.xml file
> Validation messages moved to strings.xml file

- .idea/codeStyles/Project.xml
- app/build.gradle
- app/src/main/java/mz/org/fgh/idartlite/view/reports/DispenseReportActivity.java
- app/src/main/java/mz/org/fgh/idartlite/view/reports/FILAReportActivity.java
- app/src/main/java/mz/org/fgh/idartlite/view/reports/PatientRegisterReportActivity.java
- app/src/main/res/values-pt/strings.xml
- app/src/main/res/values/strings.xml
> fixes messages and validation

- app/src/main/java/mz/org/fgh/idartlite/model/Dispense.java
- app/src/main/java/mz/org/fgh/idartlite/util/DateUtilitis.java
- app/src/main/java/mz/org/fgh/idartlite/view/patient/CreateDispenseActivity.java
- app/src/main/java/mz/org/fgh/idartlite/viewmodel/DispenseVM.java
- app/src/main/res/values-pt/strings.xml
- app/src/main/res/values/strings.xml
Adicionar os dias remanescentes a data actual de levantamento do paciente.
> Validar Aviamento de medicamento na data antes da data real de levanto

- app/src/main/java/mz/org/fgh/idartlite/view/patient/CreateDispenseActivity.java
- app/src/main/java/mz/org/fgh/idartlite/viewmodel/DispenseVM.java
Adicionar os dias remanescentes a data actual de levantamento do paciente.
Carregar data de próximo levantamento ao clicar no campo data do Próximo levantamento
> Validar Aviamento de medicamento na data antes da data real data de Levantamento 

- .idea/codeStyles/Project.xml
- app/src/main/java/mz/org/fgh/idartlite/base/activity/BaseActivity.java
- app/src/main/java/mz/org/fgh/idartlite/common/ApplicationStep.java
- app/src/main/java/mz/org/fgh/idartlite/rest/service/Patient/RestPatientService.java
- app/src/main/java/mz/org/fgh/idartlite/view/patientSearch/NewPatientSearchActivity.java
- app/src/main/java/mz/org/fgh/idartlite/viewmodel/patient/NewPatientSearchVM.java
- app/src/main/res/layout/activity_patient_home.xml
> melhorias fixes

- .idea/codeStyles/Project.xml
- app/src/main/java/mz/org/fgh/idartlite/dao/clinicInfo/ClinicInfoDaoImpl.java
- app/src/main/java/mz/org/fgh/idartlite/dao/clinicInfo/IClinicInfoDao.java
- app/src/main/java/mz/org/fgh/idartlite/model/ClinicInformation.java
- app/src/main/java/mz/org/fgh/idartlite/model/SyncClinicInformation.java
- app/src/main/java/mz/org/fgh/idartlite/rest/service/ClinicInfo/RestClinicInfoService.java
- app/src/main/java/mz/org/fgh/idartlite/rest/service/RestRunDataForTestService.java
- app/src/main/java/mz/org/fgh/idartlite/service/clinicInfo/ClinicInfoService.java
- app/src/main/java/mz/org/fgh/idartlite/service/clinicInfo/IClinicInfoService.java
- app/src/main/java/mz/org/fgh/idartlite/viewmodel/clinicInfo/ClinicInfoVM.java
- app/src/main/java/mz/org/fgh/idartlite/workSchedule/work/post/RestPostPatientDataWorkerScheduler.java
envio da informacao clinica a base central
> informacao clinica - criar editar remover  e visualizar

- .idea/gradle.xml
- app/src/main/java/mz/org/fgh/idartlite/model/ClinicInformation.java
- app/src/main/java/mz/org/fgh/idartlite/model/SyncClinicInformation.java
- app/src/main/java/mz/org/fgh/idartlite/rest/service/ClinicInfo/RestClinicInfoService.java
- app/src/main/java/mz/org/fgh/idartlite/view/clinicInfo/ClinicInfoActivity.java
- app/src/main/java/mz/org/fgh/idartlite/view/dispense/CreateDispenseActivity.java
- app/src/main/java/mz/org/fgh/idartlite/view/patientPanel/EpisodeFragment.java
- app/src/main/java/mz/org/fgh/idartlite/view/patientPanel/PatientPanelActivity.java
- app/src/main/java/mz/org/fgh/idartlite/viewmodel/clinicInfo/ClinicInfoVM.java
- app/src/main/res/layout/activity_clinic_info.xml
- app/src/main/res/layout/activity_create_dispense.xml
- app/src/main/res/layout/patient_clinic_info_row.xml
- app/src/main/res/values-pt/strings.xml
- app/src/main/res/values/strings.xml
> correcoes do teste com o CCS relacionadas a aviamento

- app/src/main/res/values/strings.xml
> Update Informação Clínica  para Vitais

- .idea/gradle.xml
- app/src/main/java/mz/org/fgh/idartlite/base/application/IdartLiteApplication.java
- app/src/main/java/mz/org/fgh/idartlite/base/rest/ServiceWatcher.java
- app/src/main/java/mz/org/fgh/idartlite/rest/service/Disease/RestDiseaseTypeService.java
- app/src/main/java/mz/org/fgh/idartlite/rest/service/Dispense/RestDispenseTypeService.java
- app/src/main/java/mz/org/fgh/idartlite/rest/service/Drug/RestDrugService.java
- app/src/main/java/mz/org/fgh/idartlite/rest/service/Episode/RestEpisodeService.java
- app/src/main/java/mz/org/fgh/idartlite/rest/service/Form/RestFormService.java
- app/src/main/java/mz/org/fgh/idartlite/rest/service/Patient/RestPatientService.java
- app/src/main/java/mz/org/fgh/idartlite/rest/service/Regimen/RestTherapeuticRegimenService.java
- app/src/main/java/mz/org/fgh/idartlite/rest/service/RestRunDataForTestService.java
- app/src/main/java/mz/org/fgh/idartlite/rest/service/Stock/RestStockService.java
- app/src/main/java/mz/org/fgh/idartlite/rest/service/TherapeuticLine/RestTherapeuticLineService.java
- app/src/main/java/mz/org/fgh/idartlite/rest/service/clinic/RestPharmacyTypeService.java
- app/src/main/java/mz/org/fgh/idartlite/view/home/ui/settings/AppSettingsFragment.java
- app/src/main/java/mz/org/fgh/idartlite/view/stock/inventory/IventoryActivity.java
- app/src/main/java/mz/org/fgh/idartlite/viewmodel/settings/SettingsVM.java
- app/src/main/java/mz/org/fgh/idartlite/viewmodel/stock/InventoryVM.java
- app/src/main/java/mz/org/fgh/idartlite/workSchedule/work/DataSyncWorker.java
- app/src/main/java/mz/org/fgh/idartlite/workSchedule/work/MetaDataSyncWorker.java
- app/src/main/java/mz/org/fgh/idartlite/workSchedule/work/get/RestGetEpisodeWorkerScheduler.java
- app/src/main/java/mz/org/fgh/idartlite/workSchedule/work/get/RestGetPatientDataWorkerScheduler.java
- app/src/main/res/drawable/ic_data.xml
- app/src/main/res/layout/activity_iventory.xml
- app/src/main/res/values-pt/strings.xml
- app/src/main/res/values/strings.xml
> Criação de notificações para sincronização

- app/src/main/AndroidManifest.xml
- app/src/main/java/mz/org/fgh/idartlite/model/ClinicInformation.java
- app/src/main/java/mz/org/fgh/idartlite/view/clinicInfo/ClinicInfoActivity.java
- app/src/main/java/mz/org/fgh/idartlite/view/dispense/CreateDispenseActivity.java
- app/src/main/java/mz/org/fgh/idartlite/viewmodel/clinicInfo/ClinicInfoVM.java
- app/src/main/res/layout/activity_clinic_info.xml
- app/src/main/res/values-pt/strings.xml
- app/src/main/res/values/strings.xml
> validacoes vitais

- app/src/main/java/mz/org/fgh/idartlite/rest/service/Dispense/RestDispenseService.java
Set int result on data diference
> Set int result on data diference

- app/src/main/AndroidManifest.xml
- app/src/main/java/mz/org/fgh/idartlite/adapter/recyclerview/dispense/PatientAwaitingDispenseReportAdapter.java
- app/src/main/java/mz/org/fgh/idartlite/dao/dispense/DispenseDaoImpl.java
- app/src/main/java/mz/org/fgh/idartlite/dao/dispense/IDispenseDao.java
- app/src/main/java/mz/org/fgh/idartlite/model/Dispense.java
- app/src/main/java/mz/org/fgh/idartlite/model/Patient.java
- app/src/main/java/mz/org/fgh/idartlite/model/Prescription.java
- app/src/main/java/mz/org/fgh/idartlite/model/ReturnedDrug.java
- app/src/main/java/mz/org/fgh/idartlite/service/dispense/DispenseService.java
- app/src/main/java/mz/org/fgh/idartlite/service/dispense/IDispenseService.java
- app/src/main/java/mz/org/fgh/idartlite/service/dispense/IReturnedDrugService.java
- app/src/main/java/mz/org/fgh/idartlite/service/dispense/ReturnedDrugService.java
- app/src/main/java/mz/org/fgh/idartlite/util/Utilities.java
- app/src/main/java/mz/org/fgh/idartlite/view/dispense/ReturnDispenseActivity.java
- app/src/main/java/mz/org/fgh/idartlite/view/patientPanel/DispenseFragment.java
- app/src/main/java/mz/org/fgh/idartlite/view/patientPanel/PatientPanelActivity.java
- app/src/main/java/mz/org/fgh/idartlite/view/reports/AbsentPatientsReportActivity.java
- app/src/main/java/mz/org/fgh/idartlite/view/reports/ReportTypeActivity.java
- app/src/main/java/mz/org/fgh/idartlite/viewmodel/dispense/AbsentPatientsReportVM.java
- app/src/main/java/mz/org/fgh/idartlite/viewmodel/dispense/AwatingPatientsReportVM.java
- app/src/main/java/mz/org/fgh/idartlite/viewmodel/dispense/ReturnDispenseVM.java
- app/src/main/res/layout/activity_absent_patients_report.xml
- app/src/main/res/layout/activity_return_dispense.xml
- app/src/main/res/layout/content_awaiting_patients_report.xml
- app/src/main/res/layout/listable_item.xml
- app/src/main/res/values-pt/strings.xml
- app/src/main/res/values/strings.xml
relatorio de pacientes faltosos
remover dispensas(details missing)
> relatorio de pacientes esperados

- app/src/main/java/mz/org/fgh/idartlite/rest/service/Patient/RestPatientService.java
- app/src/main/java/mz/org/fgh/idartlite/view/reports/AwatingPatientsGraphReportActivity.java
- app/src/main/java/mz/org/fgh/idartlite/workSchedule/work/DataSyncWorker.java
- app/src/main/java/mz/org/fgh/idartlite/workSchedule/work/get/RestGetPatientDataWorkerScheduler.java
- app/src/main/res/layout/fragment_home.xml
- app/src/main/res/values-pt/strings.xml
- app/src/main/res/values/dimens.xml
- app/src/main/res/values/strings.xml
Colocar a data/hora da ultima sincronizacao
Relatorio estatistico em forma grafica que mostra total de pacientes esperados descriminados por Regime e Tipo de Dispensa
> Melhorar de notificações para sincronização de pacientes

- app/src/main/java/mz/org/fgh/idartlite/view/reports/DispenseReportActivity.java
- app/src/main/java/mz/org/fgh/idartlite/view/reports/PatientsAwaitingReportActivity.java
- app/src/main/java/mz/org/fgh/idartlite/viewmodel/prescription/PrescriptionVM.java
- app/src/main/res/values/strings.xml
fix de actualizar prescricao
fix relatorio de dispensas no pdf
> fix de actualizar prescricao

- app/src/main/java/mz/org/fgh/idartlite/dao/prescription/IPrescriptionDao.java
- app/src/main/java/mz/org/fgh/idartlite/dao/prescription/PrescriptionDaoImpl.java
- app/src/main/java/mz/org/fgh/idartlite/service/dispense/ReturnedDrugService.java
- app/src/main/java/mz/org/fgh/idartlite/service/prescription/IPrescriptionService.java
- app/src/main/java/mz/org/fgh/idartlite/service/prescription/PrescriptionService.java
- app/src/main/java/mz/org/fgh/idartlite/view/dispense/CreateDispenseActivity.java
- app/src/main/java/mz/org/fgh/idartlite/view/prescription/PrescriptionActivity.java
- app/src/main/java/mz/org/fgh/idartlite/view/stock/inventory/IventoryActivity.java
- app/src/main/java/mz/org/fgh/idartlite/viewmodel/prescription/PrescriptionVM.java
- app/src/main/res/layout/activity_iventory.xml
bug fixes (prescricao , remover dispensa , dispensa ,inventario)
> bug fixes (prescricao , remover dispensa , dispensa ,inventario)

- app/src/main/AndroidManifest.xml
- app/src/main/java/mz/org/fgh/idartlite/adapter/recyclerview/report/DispenseDrugStatisticsReportAdapter.java
- app/src/main/java/mz/org/fgh/idartlite/service/dispense/DispenseDrugService.java
- app/src/main/java/mz/org/fgh/idartlite/service/dispense/IDispenseDrugService.java
- app/src/main/java/mz/org/fgh/idartlite/view/reports/DispenseDrugStatisticReportActivity.java
- app/src/main/java/mz/org/fgh/idartlite/viewmodel/report/DispenseDrugStatisticReportVM.java
- app/src/main/res/layout/activity_dispense_drug_statistic_report.xml
- app/src/main/res/layout/content_dispense_drug_statistics.xml
- app/src/main/res/values-pt/strings.xml
- app/src/main/res/values/strings.xml
relatorio estatistico de total de dispensas por medicamento
> relatorio estatistico de total de dispensas por medicamento

- app/src/main/java/mz/org/fgh/idartlite/viewmodel/prescription/PrescriptionVM.java
> fix prescricao

- app/src/main/java/mz/org/fgh/idartlite/view/home/ui/home/HomeFragment.java
- app/src/main/res/layout/fragment_home.xml
mudanca de cor da label da ultima sicronizacao
> mudanca de cor da label da ultima sicronizacao

- app/src/main/res/values-pt/strings.xml
- app/src/main/res/values/strings.xml
retirando o "nao" na pergunta da informacao clinica sobre a gravidez
> retirando o "nao" na pergunta da informacao clinica sobre a gravidez

- build.gradle
> voltando ao gradle normal

- app/src/main/java/mz/org/fgh/idartlite/rest/service/Dispense/RestDispenseService.java
- app/src/main/java/mz/org/fgh/idartlite/service/dispense/DispenseService.java
- app/src/main/java/mz/org/fgh/idartlite/view/clinicInfo/ClinicInfoActivity.java
- app/src/main/java/mz/org/fgh/idartlite/view/dispense/CreateDispenseActivity.java
- app/src/main/java/mz/org/fgh/idartlite/view/patientPanel/DispenseFragment.java
- app/src/main/java/mz/org/fgh/idartlite/view/prescription/PrescriptionActivity.java
- app/src/main/java/mz/org/fgh/idartlite/viewmodel/prescription/PrescriptionVM.java
fix regime terapeutico na prescricao fixes
resolucao do problema de apos a dispensa ir a tela de prescricao
> bug fix alerta de stock

- app/src/main/res/values-pt/strings.xml
- app/src/main/res/values/strings.xml
> mudanca na pergunta da tosse

- app/src/main/AndroidManifest.xml
- app/src/main/java/mz/org/fgh/idartlite/adapter/recyclerview/clinicInfo/PatientClinicInfoReportAdapter.java
- app/src/main/java/mz/org/fgh/idartlite/dao/clinicInfo/ClinicInfoDaoImpl.java
- app/src/main/java/mz/org/fgh/idartlite/dao/clinicInfo/IClinicInfoDao.java
- app/src/main/java/mz/org/fgh/idartlite/service/clinicInfo/ClinicInfoService.java
- app/src/main/java/mz/org/fgh/idartlite/service/clinicInfo/IClinicInfoService.java
- app/src/main/java/mz/org/fgh/idartlite/view/reports/PregnantPatientReportActivity.java
- app/src/main/java/mz/org/fgh/idartlite/view/reports/ReportTypeActivity.java
- app/src/main/java/mz/org/fgh/idartlite/viewmodel/clinicInfo/PregnantPatientReportVM.java
- app/src/main/java/mz/org/fgh/idartlite/viewmodel/report/AwatingPatientsStatisticReportVM.java
- app/src/main/res/layout/activity_pregnant_patient_report.xml
- app/src/main/res/layout/content_clinic_info_report.xml
- app/src/main/res/values-pt/strings.xml
- app/src/main/res/values/strings.xml
relatorio de pacientes gravidas
> relatorio de pacientes gravidas

- app/src/main/AndroidManifest.xml
- app/src/main/java/mz/org/fgh/idartlite/dao/clinicInfo/ClinicInfoDaoImpl.java
- app/src/main/java/mz/org/fgh/idartlite/dao/clinicInfo/IClinicInfoDao.java
- app/src/main/java/mz/org/fgh/idartlite/model/ClinicInformation.java
- app/src/main/java/mz/org/fgh/idartlite/service/clinicInfo/ClinicInfoService.java
- app/src/main/java/mz/org/fgh/idartlite/service/clinicInfo/IClinicInfoService.java
- app/src/main/java/mz/org/fgh/idartlite/view/reports/PregnantPatientReportActivity.java
- app/src/main/java/mz/org/fgh/idartlite/view/reports/ReportTypeActivity.java
- app/src/main/java/mz/org/fgh/idartlite/view/reports/TBSuspectPatientReportActivity.java
- app/src/main/java/mz/org/fgh/idartlite/viewmodel/clinicInfo/PregnantPatientReportVM.java
- app/src/main/java/mz/org/fgh/idartlite/viewmodel/clinicInfo/TBSuspectPatientReportVM.java
- app/src/main/java/mz/org/fgh/idartlite/viewmodel/clinicInfo/TBTracedPatientReportVM.java
- app/src/main/res/layout/activity_pregnant_patient_report.xml
- app/src/main/res/layout/activity_tb_suspect_patient.xml
- app/src/main/res/layout/content_clinic_info_report.xml
- app/src/main/res/values-pt/strings.xml
- app/src/main/res/values/strings.xml
pacientes rastreados por gravidez
> pacientes rastreados por gravidez

- app/src/main/AndroidManifest.xml
- app/src/main/java/mz/org/fgh/idartlite/view/reports/TBTracedPatientReportActivity.java
- app/src/main/res/layout/activity_tb_traced_patient_report.xml
- app/src/main/res/layout/content_clinic_info_report.xml
- app/src/main/res/values/strings.xml
- build.gradle
relatorio de pacientes rastreadas para gravidez
> relatorio de pacientes rastreadas para gravidez

- app/src/main/java/mz/org/fgh/idartlite/dao/clinicInfo/ClinicInfoDaoImpl.java
> kmudanca na query

- app/build.gradle
- app/src/main/java/mz/org/fgh/idartlite/service/dispense/DispenseService.java
- app/src/main/java/mz/org/fgh/idartlite/view/reports/ReportTypeActivity.java
- app/src/main/java/mz/org/fgh/idartlite/viewmodel/report/AdverseReactionReportVM.java
- app/src/main/java/mz/org/fgh/idartlite/viewmodel/report/PatientTreatmentFollowUpGraphicReportVM.java
- app/src/main/java/mz/org/fgh/idartlite/viewmodel/report/PatientTreatmentFollowUpReportVM.java
- app/src/main/res/values/strings.xml
Patch: Update reports labels and the app version
> Patch: Update reports labels and the app version

- app/src/main/java/mz/org/fgh/idartlite/rest/service/Episode/RestEpisodeService.java
- app/src/main/java/mz/org/fgh/idartlite/service/patient/PatientService.java
Update Data Inicio tarv control for Rest request
> Update Data Inicio tarv control for Rest request

- app/src/main/java/mz/org/fgh/idartlite/dao/clinicInfo/ClinicInfoDaoImpl.java
- app/src/main/java/mz/org/fgh/idartlite/dao/prescription/PrescriptionDaoImpl.java
ordenando prescricoes e informacoes clinicas
> ordenando prescricoes e informacoes clinicas

- app/src/main/java/mz/org/fgh/idartlite/rest/service/Stock/RestStockService.java
- app/src/main/java/mz/org/fgh/idartlite/service/stock/IStockService.java
- app/src/main/java/mz/org/fgh/idartlite/service/stock/StockService.java
correcoes sobre sicronizacao do stock
> correcoes sobre sicronizacao do stock

- app/src/main/java/mz/org/fgh/idartlite/rest/service/Patient/RestPatientService.java
- app/src/main/java/mz/org/fgh/idartlite/service/dispense/DispenseService.java
- app/src/main/java/mz/org/fgh/idartlite/service/patient/IPatientService.java
- app/src/main/java/mz/org/fgh/idartlite/service/patient/PatientService.java
actualizacao dos dados do paciente via rest
> sicronizacao do contacto telefonico

- app/src/main/java/mz/org/fgh/idartlite/viewmodel/report/AwatingPatientsStatisticReportVM.java
- app/src/main/java/mz/org/fgh/idartlite/viewmodel/report/DispensesNonSyncReportVM.java
> data de fim de relatorio

- app/src/main/java/mz/org/fgh/idartlite/adapter/recyclerview/dispense/DispenseReportAdapter.java
- app/src/main/java/mz/org/fgh/idartlite/adapter/recyclerview/patient/ContentListPatientAdapter.java
- app/src/main/java/mz/org/fgh/idartlite/view/reports/DispenseReportActivity.java
fix bug relatorio de dispensas da farmacia
> fix bug relatorio de dispensas da farmacia

- app/src/main/AndroidManifest.xml
- app/src/main/java/mz/org/fgh/idartlite/view/reports/DispenseByDispenseTypeReportActivity.java
- app/src/main/java/mz/org/fgh/idartlite/view/reports/ReportTypeActivity.java
- app/src/main/java/mz/org/fgh/idartlite/viewmodel/report/DispenseByDispenseTypeStatisticReportVM.java
- app/src/main/res/layout/activity_dispense_by_dispense_type_report.xml
- app/src/main/res/values/strings.xml
realtorio estatistico de dispenas por regime e tipo de dispensa
> realtorio estatistico de dispenas por regime e tipo de dispensa

- app/src/main/java/mz/org/fgh/idartlite/service/dispense/DispenseService.java
fix alerta de stock   , stock actual=stockMoviment
> fix alerta de stock   , stock actual=stockMoviment

- app/src/main/java/mz/org/fgh/idartlite/rest/service/Stock/RestStockService.java
Retirar sinconização do stock existente do Servidor Central para o Tablet
> Retirar sinconização do stock existente

- app/build.gradle
- app/src/main/java/mz/org/fgh/idartlite/util/DateUtilities.java
Alteração da configuracao de conversao de datas para getDefault.
Actualização para versão 2.1.0 do App
> Versão 2.1.0 do App

- app/src/main/java/mz/org/fgh/idartlite/rest/service/Dispense/RestDispenseService.java
- app/src/main/java/mz/org/fgh/idartlite/util/LoadingDialog.java
- app/src/main/java/mz/org/fgh/idartlite/view/reports/DispenseDrugGraphStatisticReportActivity.java
- app/src/main/java/mz/org/fgh/idartlite/view/reports/DispensedDrugsReportActivity.java
- app/src/main/java/mz/org/fgh/idartlite/viewmodel/dispense/DispensedDrugsReportVM.java
- app/src/main/java/mz/org/fgh/idartlite/viewmodel/patient/PatientVM.java
- app/src/main/java/mz/org/fgh/idartlite/viewmodel/report/DispenseDrugGraphStatisticReportVM.java
- app/src/main/java/mz/org/fgh/idartlite/viewmodel/report/DispenseDrugStatisticReportVM.java
- app/src/main/res/layout/activity_dispense_by_dispense_type_report.xml
- app/src/main/res/layout/activity_dispense_drug_statistic_report.xml
> Inclusão de opção para pesquisa de informação online em relatórios

- app/src/main/java/mz/org/fgh/idartlite/service/episode/EpisodeService.java
- app/src/main/java/mz/org/fgh/idartlite/service/patient/PatientService.java
- app/src/main/java/mz/org/fgh/idartlite/service/prescription/PrescriptionService.java
- app/src/main/res/values-pt/strings.xml
- app/src/main/res/values/strings.xml
- Re - Referenciamento de pacientes
> Alterações finais Release Candidate 

- app/src/main/java/mz/org/fgh/idartlite/base/viewModel/SearchVM.java
- app/src/main/java/mz/org/fgh/idartlite/model/Dispense.java
- app/src/main/java/mz/org/fgh/idartlite/rest/service/Stock/RestStockService.java
- app/src/main/java/mz/org/fgh/idartlite/service/dispense/DispenseService.java
- app/src/main/java/mz/org/fgh/idartlite/view/patientPanel/PatientPanelActivity.java
- app/src/main/java/mz/org/fgh/idartlite/view/reports/AbsentPatientsReportActivity.java
- app/src/main/java/mz/org/fgh/idartlite/workSchedule/work/get/StockWorker.java
- app/src/main/res/layout/content_awaiting_absent_patients_report.xml
- app/src/main/res/values-pt/strings.xml
- app/src/main/res/values/strings.xml
mudanca de ordem (painel paciente) adicao de ordempdf faltosos
mudancas no searchvm para imprimir todos dados no pdf
> mudanca de ordem (painel paciente) adicao de ordempdf faltosos

- app/src/main/AndroidManifest.xml
- app/src/main/java/mz/org/fgh/idartlite/base/application/IdartLiteApplication.java
- app/src/main/java/mz/org/fgh/idartlite/base/viewModel/SearchVM.java
- app/src/main/java/mz/org/fgh/idartlite/util/Utilities.java
- app/src/main/java/mz/org/fgh/idartlite/view/reports/DispenseDrugGraphStatisticReportActivity.java
- app/src/main/res/values-pt/strings.xml
- app/src/main/res/values/strings.xml
> fix relatorios

- app/src/main/java/mz/org/fgh/idartlite/util/DateUtilities.java
conversao de datas para ingles em todos metodos
> conversao de datas para ingles em todos metodos

- app/build.gradle
- app/src/main/java/mz/org/fgh/idartlite/rest/service/ClinicInfo/RestClinicInfoService.java
- app/src/main/java/mz/org/fgh/idartlite/rest/service/RestRunDataForTestService.java
- app/src/main/java/mz/org/fgh/idartlite/workSchedule/work/DataSyncWorker.java
> Release 2.2.0

- app/src/main/java/mz/org/fgh/idartlite/rest/service/Patient/RestPatientService.java
- app/src/main/java/mz/org/fgh/idartlite/service/clinic/ClinicService.java
- app/src/main/java/mz/org/fgh/idartlite/viewmodel/splash/SecondSplashVM.java
Add Functionality to allow select patients from Provincial Server U Clinic Sector
> Add Functionality to allow select patients from Provincial Server 

- .idea/sqlandroid.xml
- app/build.gradle
- app/src/main/java/mz/org/fgh/idartlite/model/Prescription.java
- app/src/main/java/mz/org/fgh/idartlite/rest/helper/ObjectRequest.java
- app/src/main/java/mz/org/fgh/idartlite/rest/service/Dispense/RestDispenseService.java
- app/src/main/java/mz/org/fgh/idartlite/rest/service/Patient/RestPatientService.java
- app/src/main/java/mz/org/fgh/idartlite/service/clinic/ClinicSectorTypeService.java
- app/src/main/java/mz/org/fgh/idartlite/view/clinicInfo/ClinicInfoActivity.java
- app/src/main/res/layout/activity_patient_home.xml
Adicionado o bloco de controlo da visualizcao da prescricao quando apresenta falta de Regime Terapeutico (QD)
Calculo de numero de fraco quando a dispensa vem da Comuniade com quantidade 0 (Rever)
Inclusao do carregamento de pacientes faltosos por US uuid 
Controlo na busca de ClinicSectorType no Ecra de LogIn
Ocultar funcionalidade de registo de paciente nos Sectores clinicos.
Coreccao do erro no registo de  Informacao Farmaceutica para mulheres acima de 45 anos de idade
> I dart mobile v1.2

- app/src/main/java/mz/org/fgh/idartlite/adapter/recyclerview/patient/ContentListPatientAdapter.java
- app/src/main/java/mz/org/fgh/idartlite/view/reports/ReportTypeActivity.java
- app/src/main/res/layout/content_patient.xml
> Bug fix on FILA report

- .idea/gradle.xml
- app/build.gradle
- app/src/main/java/mz/org/fgh/idartlite/workSchedule/work/DataSyncWorker.java
- app/src/main/java/mz/org/fgh/idartlite/workSchedule/work/MetaDataSyncWorker.java
Update last Sync label after periodic Sync
> Update last Sync label after periodic Sync

- app/build.gradle
- app/src/main/AndroidManifest.xml
- app/src/main/java/mz/org/fgh/idartlite/rest/service/Dispense/RestDispenseService.java
- app/src/main/java/mz/org/fgh/idartlite/workSchedule/executor/WorkerScheduleExecutor.java
remove // in the line for update syncLastDispenseFromUS
> Uncomment the line for update syncLastDispenseFromUS

- app/src/main/java/mz/org/fgh/idartlite/dao/dispense/DispenseDaoImpl.java
fix relatorio de faltosos , igualando o id dos pacientes no max Dispense
> fix relatorio de faltosos , igualando o id dos pacientes no max Dispense

- app/src/main/java/mz/org/fgh/idartlite/base/work/BaseWorker.java
- app/src/main/java/mz/org/fgh/idartlite/rest/service/Dispense/RestDispenseService.java
- app/src/main/java/mz/org/fgh/idartlite/rest/service/Stock/RestStockService.java
- app/src/main/java/mz/org/fgh/idartlite/service/episode/EpisodeService.java
Update search Base records to 20
> Update search Base records to 20

- app/src/main/java/mz/org/fgh/idartlite/service/episode/EpisodeService.java
Control if patient exist before save the episode
> Control if patient exist before save the episode

- app/src/main/java/mz/org/fgh/idartlite/dao/user/IUserDao.java
- app/src/main/java/mz/org/fgh/idartlite/dao/user/UserDaoImpl.java
- app/src/main/java/mz/org/fgh/idartlite/model/SyncDispense.java
- app/src/main/java/mz/org/fgh/idartlite/rest/service/Dispense/RestDispenseService.java
- app/src/main/java/mz/org/fgh/idartlite/rest/service/Patient/RestPatientService.java
- app/src/main/java/mz/org/fgh/idartlite/rest/service/RestRunDataForTestService.java
- app/src/main/java/mz/org/fgh/idartlite/service/user/IUserService.java
- app/src/main/java/mz/org/fgh/idartlite/service/user/UserService.java
- app/src/main/java/mz/org/fgh/idartlite/view/patientSearch/SearchPatientActivity.java
- app/src/main/java/mz/org/fgh/idartlite/viewmodel/home/HomeViewModel.java
- app/src/main/java/mz/org/fgh/idartlite/viewmodel/patient/PatientVM.java
Checklist
executar o Script na base de dados de monitoria:
alter table sync_temp_dispense add column username text default '' ;
alter table sync_temp_dispense add column clinicuuid text default ''
> Inclusao da clinica e user na sincronizacao da dispensa

- app/build.gradle
- app/src/main/java/mz/org/fgh/idartlite/rest/service/ClinicInfo/RestClinicInfoService.java
Change version from 2.6.0 to 2.7.0
> Change version from 2.6.0 to 2.7.0
